/**
 * @module this is the base list of messages that Exility uses internally.
 *         dataTypes.js as generated by the generator will add other messages
 *         used by the application
 */
var messagesObject = function messagesObject() {
	messages = new Object();
	messages["exilGetValueError"] = "exilGetValueError";
	messages["exilSetValueError"] = "exilSetValueError";
	messages["exilSetValueErrorOutputField"] = "exilSetValueErrorOutputField";
	messages["exilSetValueErrorTextInputField"] = "exilSetValueErrorTextInputField";
	messages["exilFillListError1"] = "exilFillListError1";
	messages["exilSetValueErrorSelectionField"] = "exilSetValueErrorSelectionField";
	messages["exilMustEnterError"] = "This Field is Mandatory";
	messages["exilPageParameterMissing"] = "exilPageParameterMissing";
	messages["exilFillListNoGrids"] = "exilFillListNoGrids";
	messages["exilValidateDependecyFailed"] = "exilValidateDependecyFailed";
	messages["exilNoIdField"] = "exilNoIdField";
	messages["exilValidateUniqueColumnsFailed"] = "exilValidateUniqueColumnsFailed";
	messages["exilIdMismatchError"] = "exilIdMismatchError";
	messages["exilGetValueError"] = "exilGetValueError";
	messages["exilSetValueErrorCheckBoxField"] = "exilSetValueErrorCheckBoxField";
	messages["exilNumberValidateFromToFailed1"] = "exilNumberValidateFromToFailed1";
	messages["exilNumberValidateFromToFailed2"] = "exilNumberValidateFromToFailed2";
	messages["exilTextValidateFromToFailed1"] = "exilTextValidateFromToFailed1";
	messages["exilTextValidateFromToFailed2"] = "exilTextValidateFromToFailed2";
	messages["exilDateValidateFromToFailed1"] = "exilDateValidateFromToFailed1";
	messages["exilDateValidateFromToFailed2"] = "exilDateValidateFromToFailed2";
	messages["exilParseDateFailedNullValue"] = "exilParseDateFailedNullValue";
	messages["exilParseDateFailedImproperFormat"] = "exilParseDateFailedImproperFormat";
	messages["exilParseDateFailedDDisNaN"] = "exilParseDateFailedDDisNaN";
	messages["exilParseDateFailedYYYYisNaN"] = "exilParseDateFailedYYYYisNaN";
	messages["exilParseDateFailedDateChanged"] = "exilParseDateFailedDateChanged";

	this.getMessage = function(win, messageId) {
		return messages[messageId];
	};
};

var systemMessages = new messagesObject();